### ISSUE TITLE
Permission issue with shared folders

### ISSUE THREAD

**Issue by mozartatplay** [pieterhop/inethi-gui#6]
I've done some pull requests to change the root of the shared directory for Nextcloud and Jellyfin to /mnt/data/share but in the ansible playbook we also need to make sure that the permission of this folder and all sub folders after being created by docker are changed to

sudo chmod -R o+w /mnt/data/share

This enables files to be written to these folders by Nextcloud and then viewed by Jellyfin

**Comment by keeganwhite** [comment]
added this in the latest commit
