### ISSUE TITLE
update setup/install instructions 

### ISSUE THREAD

**Issue by David-eb97** [pieterhop/inethi-gui#7]
the directions state to download the server version of Ubuntu 22, however in order to finish the install, the software requires a GUI to finish the install, the problem is that there is no GUI for the server version of Ubuntu 22.  
i used the following site to install a GUI as an example.

[https://phoenixnap.com/kb/how-to-install-a-gui-on-ubuntu](url)

also either in the deb file or the instructions there needs to be somewhere to update the server install, if you install the deb file with out upgrading the install, the install will fail. however if you upgrade before installing then it doesn't fail

**Comment by keeganwhite** [comment]
The GUI installer is to be run on an Ubuntu 22 desktop machine and your target device must run Ubuntu 22 server.
