### ISSUE TITLE
KeyCloak issue

### ISSUE THREAD

**Issue by David-eb97** [pieterhop/inethi-gui#8]
this is a brand new install of INethi the only thing that happened was that it spontaneously rebooted and i reran the install again thinking that it failed somehow and rebooted.  below is the error string i get when i re ran the install again.

TASK [Copy secret question ftl to Server] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [192.168.0.74]: FAILED! => {"changed": false, "msg": "Could not find or access 'resources/keycloak/secret-question.ftl'\nSearched in:\n\t/usr/lib/inethi/resources/app/backend/playbooks/files/resources/keycloak/secret-question.ftl\n\t/usr/lib/inethi/resources/app/backend/playbooks/resources/keycloak/secret-question.ftl\n\t/usr/lib/inethi/resources/app/backend/playbooks/files/resources/keycloak/secret-question.ftl\n\t/usr/lib/inethi/resources/app/backend/playbooks/resources/keycloak/secret-question.ftl on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *********************************************************************
192.168.0.74               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
Status: failed
{"code":1,"error":"The installation of keycloak failed. Error occured while executing: Copy secret question ftl to Server.\n"}

**Comment by keeganwhite** [comment]
hi there, were you running the gui or python based installer [inethi](https://github.com/iNethi/inethi) as this seems to be an error from the latter. The device is expected to restart as part of correcting user permissions.
